edition = "2021"
format_strings = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
comment_width = 100
format_code_in_doc_comments = true
wrap_comments = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
hard_tabs = true
